apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ai19n5g2m-java-quarkus
  janus-idp.io/tekton: ai19n5g2m-java-quarkus
  backstage.io/kubernetes-id: ai19n5g2m-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ai19n5g2m-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
